### ISSUE TITLE
Any performance benchmarks of sentence segmentation of Spacy vs stanza

### ISSUE THREAD

**Issue by ogencoglu** [koaning/sentence-models#4]
It seems like you utilize Spacy sentence segmenter here. Have you benchmarked [stanza](https://stanfordnlp.github.io/stanza/)'s segmenter?

**Comment by koaning** [comment]
There was a small discussion on LinkedIn about that. One conclusion seemed that if I wanted to replace spaCy that [pySBD](https://github.com/nipunsadvilkar/pySBD) would be the most interesting candidate. 

That said. I have not benchmarked it and the main goal for now is simplicity. I may just replace the `spacy_model` param with a function that can do the splitting.

**Comment by ogencoglu** [comment]
Thanks for the swift reply. Looking at the image in pySBD readme, _blingfire_ seems accurate enough but ridiculously fast. Interesting.
